---
title: "Quantifying shoreline modifications adjacent to eelgrass meadows in the Strait of Georgia Bioregion"
french_title: "Quantification des modifications du littoral adjacent aux herbiers de zostère dans la biorégion du détroit de Georgia"
year: "2023"
report_number: "3574"
author: |
  John M. Cristiani^1^
  Katherine H. Bannar-Martin^1^ and
  Emily M. Rubidge^2^
author_list: "Cristiani, J.C., Bannar-Martin, K.H, and Rubidge, E.M."
region: Pacific Region
french_region: Région du Pacifique
isbn: "978-0-660-68394-2"
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
  ^2^Institute of Ocean Sciences\
     Fisheries and Oceans Canada, 9860 W Saanich Road\
     Sidney, British Columbia, V8L 4B2, Canada\
french_address: |
  ^1^Station biologique du Pacifique\
     Pêches et Océans Canada, 3190 Hammond Bay Road\
     Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \smallskip
  ^2^Loin, très loin\
     Une autre galaxie
phone: "(555) 555-5555"
author_footnote: "Email: John.Cristiani@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
  Coastal marine ecosystems face threats from various marine and terrestrial human activities. Shoreline modifications that result from these activities can significantly impact the health and functioning of coastal biogenic habitats, including seagrass meadows. Understanding the presence and extent of shoreline modifications adjacent to seagrass meadows is therefore crucial for assessing potential human impacts to seagrass ecosystems. This technical report aims to map, characterize, and quantify shoreline modifications adjacent to known eelgrass (*Zostera marina*) meadows in the Strait of Georgia Bioregion of British Columbia. Using aerial imagery and a spatial dataset of seagrass distribution compiled from various sources, we digitized shoreline modifications within 100 meters of the coastline adjacent to each seagrass meadow. We focused on structures and areas that have been de-vegetated and altered from their natural state. We characterized modifications into six categories (road, residential, industrial, agriculture, greenspace, unclear), and we recorded additional descriptions for each category (e.g. road: paved). We found that the median percent of modified shoreline area was 9%. Of the 685 meadows analyzed 19% had no modifications, and 9% were more than 50% modified. The dominant modification type across the study area was residential development. The resulting dataset provides valuable information for assessing land use patterns and predicting potential impacts to nearshore ecosystems. Future efforts should continue to add to and refine the shoreline modification dataset as seagrass spatial datasets are updated. This study highlights the importance of managing seagrass within its broader seascape and landscape context, and it emphasizes the need for ongoing data collection and analysis to inform effective seagrass management strategies.
french_abstract: |
  Les écosystèmes marins côtiers sont menacés par diverses activités humaines marines et terrestres. Les modifications du littoral résultant de ces activités peuvent avoir une incidence significative sur la santé et le fonctionnement des habitats biogéniques côtiers, y compris les herbiers marins. Il est donc essentiel de comprendre la présence et l’étendue des modifications du littoral à proximité des herbiers marins pour évaluer les répercussions potentielles de l’humain sur les écosystèmes d’herbiers marins. Ce rapport technique vise à cartographier, caractériser et quantifier les modifications du littoral à proximité d’herbiers connus de zostère (Zostera marina) dans la biorégion du détroit de Georgia, en Colombie-Britannique. À l’aide d’images aériennes et d’un ensemble de données spatiales sur la répartition des herbiers marins compilées à partir de diverses sources, nous avons numérisé les modifications du littoral dans un rayon de 100 mètres de la côte adjacente à chaque herbier marin. Nous nous sommes concentrés sur les structures et les zones qui ont été dévégétalisées et modifiées par rapport à leur état naturel. Nous avons classé les modifications en six catégories (route, milieu résidentiel, milieu industriel, milieu agricole, espace vert, non défini) et nous avons enregistré des descriptions supplémentaires pour chaque catégorie (par exemple, route pavée). Nous avons constaté que le pourcentage médian de la superficie modifiée du littoral était de 9 %. Sur les 685 herbiers analysés, 19 % n’ont subi aucune modification et 9 % ont été modifiés à plus de 50 %. Le type de modification dominant dans la zone d’étude est le développement résidentiel. L’ensemble de données qui en a résulté fournit de l’information précieuse pour l’évaluation des schémas d’utilisation des sols et la prévision des répercussions potentielles sur les écosystèmes littoraux. Il faut continuer à compléter et à améliorer l’ensemble de données sur la modification du littoral à mesure que les ensembles de données spatiales sur les herbiers marins sont mis à jour. Cette étude met en évidence l’importance de la gestion des herbiers marins dans le contexte plus large du paysage marin et terrestre, et souligne la nécessité d’une collecte et d’une analyse continues des données afin d’élaborer des stratégies efficaces pour la gestion des herbiers marins.
output:
 csasdown::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: false
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: true
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdown::render('_bookdown.yml')
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/library_all.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
library(kableExtra)
```
